### ISSUE TITLE
Recent 1.2.0 still has 1.1.2 as metadata

### ISSUE THREAD

**Issue by geoffdavis** [RogueProeliator/IndigoPlugins-Plex-Server-Manager-Plugin#3]
When I try to install version 1.2.0, Indigo prompts and says 'Plugin "Plex Media Server Manager" v1.1.2" is already installed.'

Looks like the metadata file needs to be bumped for the release.

**Comment by RogueProeliator** [comment]
I sincerely apologize... I must have my notification settings wrong for this project as I never got word that you posted this.  I know it is too late and other releases are out there but just wanted to let you know I didn't purposely ignore you!
