### ISSUE TITLE
Bad link on Indigo Forum

### ISSUE THREAD

**Issue by balthisar** [RogueProeliator/IndigoPlugins-Plex-Server-Manager-Plugin#5]
The link at the top of http://forums.indigodomo.com/viewtopic.php?f=163&t=13755 takes you to https://github.com/RogueProeliator/IndigoPlugins-Onkyo-Receiver-Network-Remote instead of this repo.

**Comment by RogueProeliator** [comment]
Got it - thanks for reporting!
